### ISSUE TITLE
The custom PotreeConverter won't build

### ISSUE THREAD

**Issue by mamayoleksandr** [NLeSC/Massive-PotreeConverter#1]
It gives following errors on ubuntu linux 14.04 64 bit:
/usr/local/src/BIG_PC/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp: In constructor ‘PTXPointReader::PTXPointReader(std::string)’:
/usr/local/src/BIG_PC/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:83:18: error: use of deleted function ‘std::basic_fstream<char>& std::basic_fstream<char>::operator=(const std::basic_fstream<char>&)’
     this->stream = fstream(*(this->currentFile), ios::in);
                  ^
In file included from /usr/local/src/BIG_PC/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:0:
/usr/include/c++/4.8/fstream:776:11: note: ‘std::basic_fstream<char>& std::basic_fstream<char>::operator=(const std::basic_fstream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_fstream : public basic_iostream<_CharT, _Traits>

.....

In file included from /usr/include/c++/4.8/ios:43:0,
                 from /usr/include/c++/4.8/istream:38,
                 from /usr/include/c++/4.8/fstream:38,
                 from /usr/local/src/BIG_PC/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:
/usr/include/c++/4.8/streambuf:802:7: error: ‘std::basic_streambuf<_CharT, _Traits>::basic_streambuf(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<char>]’ is private
       basic_streambuf(const basic_streambuf& __sb)
       ^
In file included from /usr/local/src/BIG_PC/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:0:
/usr/include/c++/4.8/fstream:72:11: error: within this context
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
/usr/local/src/BIG_PC/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp: In member function ‘bool PTXPointReader::doReadNextPoint()’:
/usr/local/src/BIG_PC/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:216:26: error: use of deleted function ‘std::basic_fstream<char>& std::basic_fstream<char>::operator=(const std::basic_fstream<char>&)’
             this->stream = fstream(*(this->currentFile), ios::in);
                          ^
make[2]: *** [PotreeConverter/CMakeFiles/PotreeConverter.dir/src/PTXPointReader.cpp.o] Error 1
make[1]: *** [PotreeConverter/CMakeFiles/PotreeConverter.dir/all] Error 2
make: *** [all] Error 2

thanks,

Alex.

**Comment by oscarmartinezrubi** [comment]
Hi,

Did you use the fix_fstream branch?

git clone -b fix_fstream https://github.com/oscarmartinezrubi/PotreeConverter.git

There is some issue with the default branch of PotreeConverter so you need to use that one. If that does not work I will try in an Ubuntu and see what else may be going on.

**Comment by mamayoleksandr** [comment]
Heya,

yep fix_fstream branch seems to be fixed.

thanks.
