### ISSUE TITLE
lassort command on linux

### ISSUE THREAD

**Issue by goord** [NLeSC/Massive-PotreeConverter#8]
The sort_index.py script calls the windows binary lassort.exe. To enable this on linux, make the user define the environment variable LASSORT (wine <path to lassort.exe>) and use this in the python script.

**Comment by goord** [comment]
rev. 6791c9fa667afe34b70f9ac9a902bcbdbafbbe01

**Comment by romulogoncalves** [comment]
Documentation about it:
https://github.com/NLeSC/Massive-PotreeConverter/commit/8e43cb0c9045edc32de11c48e656392f11955fd8
